## Day Objective
- NumPy

### Python Libraries
- NumPy
- Pandas
- Matplotlib
- Seaborn
- SciKit Learn
- Tesnorflow
- Keras

### NumPy (Numerical Python)
- Numpy is one of the python library mathematical computation at a faster and easier way.

#### Installation and Importing numpy
- pip install numpy
- or 
- conda install numpy

In [1]:
import numpy as np

In [2]:
# version
np.__version__

'1.20.3'

In [3]:
# NumPy methods
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

**Create numpy arrays in different ways**
- List, Tuple

In [4]:
## 1-Dimensional array
n1 = np.array([1,10,100,1000])
n1

array([   1,   10,  100, 1000])

In [7]:
print(type(n1))
print(n1.ndim)  # to check no.of dimensions
print(n1.itemsize) # memory used by each element in bytes

<class 'numpy.ndarray'>
1
4


In [8]:
print(n1.dtype)

int32


In [10]:
n1 = np.array([1.9,10,100,1000])
print(n1.dtype)

float64


In [11]:
n1 = np.array([1.9,10,100,1000,'GVP'])
print(n1.dtype)
# <U32 --> Unicode 32 char datatype

<U32


In [12]:
## 2-Dimensional Array
#### np.array( [ [ row1 ], [ row2 ], .... , [ rowN ] ] )
n2 = np.array([ [1,2,3,4],[5,6,7,8] ])
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
print(n2.ndim)
print(n2.shape) # no.of rows and columns

2
(2, 4)


In [15]:
## 3-Dimensional or multi-dimensional
### np.array([ [ [],[] ] ])
n3 = np.array([ [ [1,2,3],[10,20,30] ] ])
n3

array([[[ 1,  2,  3],
        [10, 20, 30]]])

In [16]:
print(n3.ndim)

3


**Why Numpy? When we have list**

In [17]:
list1 = [1,1,1]
numpy1 = np.array([1,1,1])

In [18]:
print(list1 + 9)

TypeError: can only concatenate list (not "int") to list

In [19]:
print(numpy1 + 9)

[10 10 10]


#### Advantages of NumPy
- NumPy array are more compact than List
- NumPy take less storage space than list and execution is very fast

#### NumPy Methods
- np.arange()
- np.linspace()
- np.ones()
- np.zeros()
- Reshape
- Statistical Methods
- Roandom methods

In [20]:
## for loop Vs np.arange()

In [21]:
for i in range(10,20):
    print(i)

10
11
12
13
14
15
16
17
18
19


In [22]:
range(10,20)

range(10, 20)

**np.arange()**

In [59]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [25]:
np.arange(0,101,5)
## 0 : start value, 101: stop value, 5: step size

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [61]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

**np.linspace()**

In [26]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
1.05263158 - 0.52631579

0.52631579

In [28]:
6.8421052 - 6.31578947

0.5263157299999994

In [29]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [30]:
np.linspace(0,10,20, retstep = True)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
 0.5263157894736842)

**np.ones()**

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.ones([3, 2, 4])
##  3 --> no.of matrices
##  2 --> no.of rows
##  4 --> no.of columns

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
np.ones(5, dtype = int)

array([1, 1, 1, 1, 1])

In [35]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. note::
            

**np.zeros**: Similar to np.ones()
- Try np.zeros() by yourself

**Reshape**
- Giving a new shape to an array

In [37]:
a = np.array([[1,10,20,2],[11,7,102,18]])
a

array([[  1,  10,  20,   2],
       [ 11,   7, 102,  18]])

In [38]:
a.shape

(2, 4)

- The product of rows and columns in the new array should be equal to total no of elements.

In [39]:
# 2 rows and 4 columns
## 2 * 4 = 8
## 4 * 2 = 8
## 8 * 1 = 8
## 1 * 8 = 8

In [40]:
a.reshape(4,2)

array([[  1,  10],
       [ 20,   2],
       [ 11,   7],
       [102,  18]])

In [41]:
a.reshape(4,1)

ValueError: cannot reshape array of size 8 into shape (4,1)

In [42]:
a.reshape(1,8)

array([[  1,  10,  20,   2,  11,   7, 102,  18]])

**Statistical Methods**

In [43]:
a1 = np.arange(10,30)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [44]:
len(a1)

20

In [45]:
a2 = a1.reshape(4,5)
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [49]:
print(np.max(a2))
print(np.min(a2))
print(np.argmax(a2)) # returns index of maximum value
print(np.argmin(a2)) # returns index of minimum value

29
10
19
0


In [51]:
print(np.sum(a2))
print(np.mean(a2))
print(np.median(a2))

390
19.5
19.5


In [54]:
print(np.log(10))
print(np.log2(10))
print(np.log10(10))

2.302585092994046
3.321928094887362
1.0


In [57]:
print(np.sin(3.14/6))
print(np.cos(3.14/3))
print(np.tan(3.14/4))

0.4997701026431024
0.5004596890082058
0.9992039901050427


In [58]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp